### ISSUE TITLE
Pick one

### ISSUE THREAD

**Issue by ZachBeta** [treznick/ContinuityHubot#4]
/(pick|choose) one: (.*)/

results.split(',').split(' or ')

**Comment by treznick** [comment]
what's the issue here?

**Comment by ZachBeta** [comment]
Had a passing thought that "pick one" could also have "choose one"
And it could use "or" instead of "comma" but it's not strictly needed.

**Comment by treznick** [comment]
1f4f683

363f5a1

pushed and deployed
